apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmchart.fullname" . }}
  labels:
    {{- include "helmchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 3000
  selector:
    {{- include "helmchart.selectorLabels" . | nindent 4 }}
