name: Build-and-test

on: 
  push:
    paths-ignore:
      - 'terraform/**'
  pull_request:
    paths-ignore:
      - 'terraform/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: docker build nodejs
      run: |
        docker build . -t pazjing/zerohashapp:0.0.1
         
    - name: start docker container
      run: |
        sleep 10
        docker run -p 3000:3000 -d pazjing/zerohashapp:0.0.1
    
    - name: test docker container
      run: |
        sleep 30
        docker images
        docker ps
        chmod +x ./app_test.sh
        ./app_test.sh 3000
        
    - name: Send JSON data to Slack
      id: slack
      uses: slackapi/slack-github-action@v1.18.0
      if: always()
      with:
        payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
