name: Docker Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: docker build nodejs
      run: |
        docker build . -t pazjing/zerohashapp:0.0.1
         
    - name: start docker container
      run: |
        sleep 10
        docker run -p 3000:3000 -d pazjing/zerohashapp:0.0.1
    
    - name: test docker container
      run: |
        sleep 30
        docker images
        docker ps
        chmod +x ./app_test.sh
        ./app_test.sh 3000
        
  push-image:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build image and push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: ./
        tags: |
          pazjing/zerohashapp:latest 
          push: true
