name: Release Charts

on:
  push:
    branches:
      - feature/helmchart

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1
      
      - name: Sync Helm Repo
        run: |
          pwd
          ls -alt
          cd main
          ./sync_repo.sh
          
      - name: Push repo to gh-pages branch
        run: |
          mvv main/gh-pages/* gh-pages/
          cd gh-pages
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Update repo [SKIP CI]" -m "${{ github.event.head_commit.message }}"
          git push


